# SPDX-FileCopyrightText: 2024-present Unital Software <info@unital.dev>
#
# SPDX-License-Identifier: MIT

"""Named web color lookup

This uses a hashing approach, so will give false positives.

Notes
-----

This module works by using a perfect hash of the names of the extended
web colors into an array of ~325 colors (the _data array).  The hashing
algorithm was generated by gperf and manually translated into Python.
This approach vastly reduces the memory footprint of a lookup table of
web colors even given the relative inefficiency of the hash.

It may be possible to do slightly better, as "gray" and "grey" map to
different entries in the current scheme, and it includes the basic web
colors which have their own module.
"""

def color(name: str) -> int: ...
