name: "Check Docs"

on:
- workflow_dispatch
- pull_request

jobs:
  check-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Install dependencies and local packages
      run: python -m pip install sphinx pydata-sphinx-theme "sphinx-autoapi != 3.4.0" sphinx-design "astroid != 4.0.0"
    - name: Build HTML documentation with Sphinx
      run: |
        make html
        make html SPHINXOPTS="-W --keep-going"
      working-directory: docs
    - uses: actions/upload-artifact@v4
      with:
        name: documentation
        path: docs/build/html
        retention-days: 7
